gems:
  - jekyll-seo-tag
title: U.S. NSF SciStream Project
description: Homepage of the Architecture and toolkit for data stream-ing between federated science instruments Project. 
url: https://scistream.github.io
social:
  name: U.S. NSF SciStream Project
  links:
    - https://scistream.github.io
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
